// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seahgodnrmzaclsewrtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_7D0KGTh1ebtO60RPji6C6A_04xhBD8N";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);